# Generated by Django 4.1.7 on 2023-03-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_order_payment_complete_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Khalti', 'Khalti'), ('eSewa', 'eSewa')], default='Cash On Delivery', max_length=100, null=True),
        ),
    ]
